from datetime import timedelta

SESSION_COOKIE_NAME = "session_id"
SESSION_DURATION = timedelta(hours=2)

SECRET_KEY = "jGn{a~vT}X914}A]$xe"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 360
REFRESH_TOKEN_EXPIRE_MINUTES = 43200
